### ISSUE TITLE
[Feat] gpt api 호출

### ISSUE THREAD

**Issue by yunji118** [ewha-cse-HACK/HACK_Server#1]
### Description
백엔드에서 gpt 호출하는 로직 작성

### Todo
> 1. [x]  전체 로직 구상
> 2. [x]  프론트에서 들어온 요청에 대해 gpt 호출하는 로직 작성

**Comment by minji1289** [comment]
[feat] GPT api 호출: e11da2cb4a43ea1741abb1e302d704749f43a2c0
[docs] .gitignore에 ChatGPTConfig 파일 추가: ca616e0a51c2014fdfece83030f3b439efb812f9
[feat] apiKey 노출 제거: 08d2e1da8b839af7989e7ba0f7445671d9cd027c
