### ISSUE TITLE
[feat] 페르소나 설정

### ISSUE THREAD

**Issue by yunji118** [ewha-cse-HACK/HACK_Server#19]
### Description
반려동물 페르소나 입력받기

### Todo
> 1. [x]  종
> 2. [x]  이름 및 성격
> 3. [x]  호칭 및 정보
> 4. [x]  entity
> 5. [x]  repo

**Comment by minji1289** [comment]
[feat] 반려동물 이름 및 성격 설정: a300569e46d9d06766e70eb024bd34de1ed7bd38

[fix] 반려동물 종, 이름, 성격 한번에 받아오기: f01916e0e823148db5c0bb934f99caf7d0e153f2

[fix] 페르소나 설정시 Character 객체 받아오는 것으로 버그 수정: 7ecb44701c68fe113fa9c594558db1d5edd112ab
