### ISSUE TITLE
[Feat]stream 적용

### ISSUE THREAD

**Issue by yunji118** [ewha-cse-HACK/HACK_Server#3]
### Description
reload 없이 답장을 받기 위해 stream 설정

### Todo
> 1. [ ]  stream 공부
> 2. [ ]  stream 설정 및 postman 확인
> 3. [ ] GPT에서 이전 대화 내역 기억하는 메커니즘 이해하기

**Comment by minji1289** [comment]
- [ ] GPT에서 이전 대화 내역 기억하는 메커니즘 이해하기
