### ISSUE TITLE
[feat] 페르소나 적용하기

### ISSUE THREAD

**Issue by yunji118** [ewha-cse-HACK/HACK_Server#35]
### Description
GPT에 페르소나 적용하기

### Todo
> 1. [x]  system 명령어 작성
> 2. [x]  페르소나 바탕으로 명령어 작성
> 3. [x]  테스트

**Comment by minji1289** [comment]
### GPT 호출시 Role 수정
[fix] RequestBody Role Assigned: 886078c9dde85b3acdf298ca8afe35b8fa37e7e3
