### ISSUE TITLE
[feat] s3 버킷 생성 및 연결

### ISSUE THREAD

**Issue by yunji118** [ewha-cse-HACK/HACK_Server#39]
### Description
프로필 사진, 커뮤니티 사진 업로드에 필요한 s3 버킷 환경 구축

### Todo
> 1. [x]  s3 버킷 생성
> 2. [x]  spring과 연결
> 3. [x]  테스트

**Comment by minji1289** [comment]
### s3 초기 설정시 bug fix
[fix] S3 DI(의존성 주입) 오류 해결: f8719de2d2c0e71a88b145952e7adf963759a5ef
