### ISSUE TITLE
[feat] 도메인주소 변경

### ISSUE THREAD

**Issue by yunji118** [ewha-cse-HACK/HACK_Server#64]
### Description
도메인 구매 및 설정에 따른 코드 수정

### Todo
> 1. [ ]  코드 변경
> 2. [ ]  api 명세서에 반영
> 3. [ ]  postman 수정

**Comment by minji1289** [comment]
### 로드밸런서 Health Check하는 코드 작성
[feat] 로드밸런서 health check: 09d442b04798c4484e099ad0c42c6f02edab26cc


### 도메인 구매 및 설정에 따른 코드 수정
[fix] 도메인 수정 c069fc9d1bd75233f473a31f381514ca994aff46
cf) 이후 발생한 에러 및 해결 로그 #90 


### CORS
도메인 변경에 따른 CORS 에러 발생 #84 
[fix] CORS 수정: 470be65b3449641e05cf542f6a13c4b72368e0ac
